### ISSUE TITLE
Add a CRD to record the Rollout release process

### ISSUE THREAD

**Issue by hantmac** [openkruise/rollouts#10]
From the design doc of `rollouts`, I know that the `rollouts` resource is bound to a deployment or cloneset, which is a `one to one` mode, we should record the information such as pod names, pod ips, deploy strategy...  when user do a deploy action.

**Comment by FillZpp** [comment]
Yeah, a history record is much useful for rollout tracing. Maybe we should decide which information should be recorded. For example, currently we don't want to listwatch pods in kruise-rollout, so how to record the pod names will be a problem.

**Comment by hantmac** [comment]
Or maybe user can record the deploy information by themself. 🤔

**Comment by zmberg** [comment]
https://github.com/openkruise/rollouts/pull/27
