### ISSUE TITLE
What are the advantages and disadvantages of the argo rollouts and the kruise rollouts

### ISSUE THREAD

**Issue by chestarss** [openkruise/rollouts#119]

**Comment by veophi** [comment]
The biggest difference between Kruise-Rollout and Argo-Rollout is that Argo-Rollout itself is a Workload, which was designed to replace Deployment; Kruise-Rollout is a bypass architecture designed to enhance the capability of Deployment.

For instance:
- **When you want to use Argo-Rollout:**  you **MUST** find a way to migrate your Workloads and Pods to Argo-Rollout; and when you no longer want it, you have to also find a way to migrate back;

- **When you want to use Kruise-Rollout:** you only need to apply the Rollout configuration **WITHOUT** migrating your Workloads and Pods. When you no longer need it, you can just delete it at any time (even during the publishing process);

_**In general, Kruise-Rollout is to enhance the ability of Workload, not replace your Workload !!!**_

**Comment by chestarss** [comment]
@veophi Thank you very much for your answer. I think I already know what to choose.
