### ISSUE TITLE
开发文档需求

### ISSUE THREAD

**Issue by git2017-jpg** [openkruise/rollouts#124]
希望能够有一份开发文档，整体架构，依赖关系和本地运行的文档

**Comment by veophi** [comment]
> 希望能够有一份开发文档，整体架构，依赖关系和本地运行的文档

@git2017-jpg  Yes.  The documents are coming soon!

**Comment by zmberg** [comment]
@git2017-jpg 看看这个文档呢，https://openkruise.io/rollouts/introduction

**Comment by git2017-jpg** [comment]
> @git2017-jpg 看看这个文档呢，https://openkruise.io/rollouts/introduction

如果有一份dev的运行文档就好了，和kruise的类似https://github.com/openkruise/kruise/tree/master/docs/contributing，对开发者友好的帮助文档

**Comment by MrSumeng** [comment]
如果我没有理解错，你是想在本地/测试环境运行 rollouts ，但不知道如何入手，所以希望有一份开发文档帮助你解决这个问题？
@git2017-jpg

**Comment by veophi** [comment]
https://github.com/openkruise/rollouts/blob/master/docs/contributing/debug.md#third-step-deploy-your-kruise-rollout-with-a-deployment

@git2017-jpg  @MrSumeng

**Comment by git2017-jpg** [comment]
@MrSumeng @veophi 是的，已经本地运行成功
