### ISSUE TITLE
canary release支持Advance Statefulset，CloneSet类型的workload

### ISSUE THREAD

**Issue by a932846905** [openkruise/rollouts#132]
基于已接入openKruise workload类型（Advance Statefulset，CloneSet）的应用，想实现金丝雀发布，加强发布质量的保障。考虑到openkruise社区已有rollouts，希望可以支持到openkruise 的workload类型，方便应用接入。

**Comment by zmberg** [comment]
@a932846905 支持的昂。https://openkruise.io/rollouts/user-manuals/basic-usage
