### ISSUE TITLE
[feature] support disable rollout

### ISSUE THREAD

**Issue by sumengzs** [openkruise/rollouts#151]
有些情况下，虽然我们的定义并应用了一个rollout资源，但我们并不想启用这个资源，当前场景并不支持此功能，希望能够支持。
`Disabled` 为 `true` 表示禁用此 Rollout。
禁用时：
1. Webhook 不会将 `workload.Spec.Paused` 修改为 `true`。
2. 当工作负载发生变化时，`watch handles` 不会将此 Rollout 添加到队列中。
3. 如果 Rollout 正在运行，它将放弃 Rollout 并重置工作负载更新策略。
4. 对于相同的工作负载，同一时间只能启用一个 Rollout。但可以存在多个已经被禁用的 Rollout。

```go
// RolloutSpec defines the desired state of Rollout
type RolloutSpec struct {
	// INSERT ADDITIONAL SPEC FIELDS - desired state of cluster
	// Important: Run "make" to regenerate code after modifying this file
	// Disabled indicates disable this Rollout, Webhook won't modify workload .Spec.Paused to true.
	// Watch handles won't add this rollout to queue when workload changes.
	// If Rollout is running, it will give up rollout and reset workload update strategy.
	// Only one rollout can be enabled for a same workload as the same time.
	Disabled bool
	...
}
```

**Comment by furykerry** [comment]
@Kuromesi 
> 对于相同的工作负载，同一时间只能启用一个 Rollout。但可以存在多个已经被禁用的 Rollout。
what is the cases of keep multiple disabled rollout? can you share the user story ?

**Comment by sumengzs** [comment]
@furykerry 
> what is the cases of keep multiple disabled rollout? can you share the user story ?

这只是一个扩展能力，不是必须的。多个 rollout 代表了多种策略，用户可以根据需求选择一种策略来使用，当然，用户可以不用如此去做，他可以通过修改原有的 rollout 来达到目的；同时存在的多个被禁用的 rollout 仅仅是提供了选择的能力，如此而已。
