### ISSUE TITLE
Rollout user, best practice documentation construction

### ISSUE THREAD

**Issue by zmberg** [openkruise/rollouts#18]

**Comment by xsyl1124** [comment]
Rollouts 的操作文档，哪里有哈？多谢

**Comment by zmberg** [comment]
In progress, the last two weeks will be submitted

**Comment by xsyl1124** [comment]
我们的业务部署在阿里云的 ECS 上，
内部服务之间 http 调用通过内网 SLB 转到 ECS，
由于流量较大，每次发布的时候，
先将 SLB 的权重调成0，然后更新服务，再依次将SLB 的权重由 0 调整到100。
如果业务迁移到 K8S 中，K8S 的 service 就相当于内网SLB，
发现 service 不能根据权重动态的调整 pods 的流量
请问 rollouts 能解决这个问题么？

**Comment by xsyl1124** [comment]
也就是 rollouts 有没有动态调整 service 权重的能力？

**Comment by zmberg** [comment]
> 也就是 rollouts 有没有动态调整 service 权重的能力？
可以解决的

**Comment by zmberg** [comment]
> Rollouts 的操作文档，哪里有哈？多谢
https://github.com/openkruise/rollouts/blob/master/docs/getting_started/introduction.md
