### ISSUE TITLE
无法删除rollout

### ISSUE THREAD

**Issue by Gourds** [openkruise/rollouts#186]
在华为CCE集群中使用

创建rollout后有问题，进行删除时发现无法删除。rollout状态一直处于Terminating状态
test-demo  demo         Terminating   3             Completed      workload deployment is completed   94m

怎么才能删除呢？以下是controller的报错
I1211 05:14:13.710022       1 leaderelection.go:352] lock is held by kruise-rollout-controller-manager-7df845874c-wqkwp_f4eda89f-b619-4000-86f3-3b0f6550d7ab and has not yet expired
I1211 05:14:13.710044       1 leaderelection.go:253] failed to acquire lease kruise-rollout/71ddec2c.kruise.io

**Comment by Gourds** [comment]
另外在CCE中，使用openkruise rollout 会导致  华为负载显示 升级关闭，然后rollout会hang住，一直显示Progressing 如
`ops-tools   rollouts-canary-demo   Progressing   3             Completed      workload deployment is completed   21m`

**Comment by furykerry** [comment]
> 另外在CCE中，使用openkruise rollout 会导致 华为负载显示 升级关闭，然后rollout会hang住，一直显示Progressing 如
can you provide the problematic rollout and workload yaml so that we can try to reproduce the problem ?

**Comment by zhengjr9** [comment]
kubectl get lease -n kruise-rollout 查看现在那个实例是leader，查看错误日志，删除不掉可能是因为Finalizers没有删除，可能是哪个地方卡住导致无法清理该finalizers

**Comment by zhengjr9** [comment]
手动edit删除该finalizers可以清理掉这类数据

**Comment by Gourds** [comment]
这样可以删除
```sh
kubectl patch rollout/rollouts-canary-demo -p '{"metadata":{"finalizers":[]}}' --type=merge -n ops-tools
```
