### ISSUE TITLE
kruise-api rollout api 版本与controller 不一致

### ISSUE THREAD

**Issue by Abb1513** [openkruise/rollouts#196]
- 安装rollout版本
 `helm install kruise-rollout openkruise/kruise-rollout ` # 0.5.0
- rollout api 的版本
![image](https://github.com/openkruise/rollouts/assets/35590533/823ea298-9c3f-4572-9a5c-4c11e078330b)
![image](https://github.com/openkruise/rollouts/assets/35590533/9b4790db-d6bf-427b-97a2-9c0b8867a91e)
- 实际controller 使用版本
![image](https://github.com/openkruise/rollouts/assets/35590533/ce413616-e773-4fbf-84ba-da10a0b1b724)
字段对不上

**Comment by furykerry** [comment]
the kruise-api is not yet synced rollout 0.5.0 API, i will update the api soon

**Comment by Abb1513** [comment]
请问有大概时间嘛。谢谢

**Comment by sailingchen** [comment]
# kubectl-kruise 0.5.0, the error case this Bug ? run Command:
kubectl kruise rollout approve rollout/rollouts-example  -n default
```
error: no kind "Rollout" is registered for version "rollouts.kruise.io/v1beta1" in scheme "pkg/runtime/scheme.go:100"
```

**Comment by furykerry** [comment]
we add a new repo for [kruise rollout api](https://github.com/openkruise/kruise-rollout-api) alone, plz use the v0.5.0 version
