### ISSUE TITLE
kruise rollout could support all traffic convert to gray environments then delete old product environments when rollout going done. 

### ISSUE THREAD

**Issue by zq200618** [openkruise/rollouts#26]
Current, when rollout going done, the product environment will firstly rolling update with the product traffic on, then convert all traffic to product environment, then delete gray environments. It will have a  problem: if two application name A and B have call dependency, 
They rolling update pod concurrently will lead to traffic confusion: the traffic flow from A product environments may flow to B gray environments.

Because the gray environment will be new product environment. the gray workload name should support config by user when it start rollout.

**Comment by zmberg** [comment]
I can assume that what you want is the current vela rollout fully managed approach, where the deployment name is incremented, e.g. deployment-1, deployment-2...

So there is a problem, how to be compatible with HPA etc.? Because the deployment name is changed, hpa has no way to configure?

**Comment by zmberg** [comment]
> I think the gray environment should create gray HPA and others when it created. 
If canary hpa is created as soon as the canary deployment is created, then canary hpa will fight with rollout and reconcile replicas together.

> gray HPA and others
These resources may require a third-party platform to convert, and rollout is not suitable for handling this convert.

**Comment by zq200618** [comment]
> > I think the gray environment should create gray HPA and others when it created.
> 
> If canary hpa is created as soon as the canary deployment is created, then canary hpa will fight with rollout and set replicas together.
> 
> > gray HPA and others
> 
> These resources may require a third-party platform to convert, and rollout is not suitable for handling this convert.

we could discuss it offline
