### ISSUE TITLE
Deploy Business Application error

### ISSUE THREAD

**Issue by xiao-jay** [openkruise/rollouts#30]
env:mac,minikube
the yaml file is https://github.com/openkruise/rollouts/blob/master/docs/tutorials/basic_usage.md#1-deploy-business-application-contains-deployment-service-and-ingress
problem:when i enter ```kubectl apply -f echoserver.yaml```and  ```kubectl get pods```,i will get pods error,such as 
```
NAME                                                             READY   STATUS    RESTARTS      AGE
echoserver-56b6c7cc94-5qslt                                      0/1     Error     2 (17s ago)   22s
echoserver-56b6c7cc94-dwqqz                                      0/1     Error     2 (18s ago)   22s
echoserver-56b6c7cc94-pt6th                                      0/1     Error     2 (17s ago)   22s
echoserver-56b6c7cc94-tkw26                                      0/1     Error     2 (17s ago)   22s
echoserver-56b6c7cc94-xggxs                                      0/1     Error     2 (17s ago)   22s
```
```
➜  kubenetes kubectl describe pod echoserver-56b6c7cc94-5qslt
Name:         echoserver-56b6c7cc94-5qslt
Namespace:    default
Priority:     0
Node:         minikube/192.168.58.2
Start Time:   Sun, 08 May 2022 18:57:03 +0800
Labels:       app=echoserver
              pod-template-hash=56b6c7cc94
Annotations:  <none>
Status:       Running
IP:           172.17.0.22
IPs:
  IP:           172.17.0.22
Controlled By:  ReplicaSet/echoserver-56b6c7cc94
Containers:
  echoserver:
    Container ID:   docker://5773ea0bc0ee021c19ae812c9c30d2f6c8cd719921dfb6230863c7ec97b09ec2
    Image:          cilium/echoserver:1.10.2
    Image ID:       docker-pullable://cilium/echoserver@sha256:f8c125b8ad412c65be38c721463737e4e80721208c744cbacc2a8977b61441c6
    Port:           8080/TCP
    Host Port:      0/TCP
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Sun, 08 May 2022 20:04:22 +0800
      Finished:     Sun, 08 May 2022 20:04:23 +0800
    Ready:          False
    Restart Count:  18
    Environment:
      PORT:  8080
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-nzdg9 (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  kube-api-access-nzdg9:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason   Age                  From     Message
  ----     ------   ----                 ----     -------
  Warning  BackOff  57s (x328 over 70m)  kubelet  Back-off restarting failed container
```

```
➜  kubenetes kubectl logs echoserver-56b6c7cc94-5qslt
Generating self-signed cert
Generating a 2048 bit RSA private key
...........+++
................................................................+++
writing new private key to '/certs/privateKey.key'
-----
Starting nginx
2022/05/08 12:04:23 [error] 24#24: failed to initialize Lua VM in /etc/nginx/nginx.conf:88
nginx: [error] failed to initialize Lua VM in /etc/nginx/nginx.conf:88
```
**i don't know where to look /etc/nginx/nginx.conf:88,and why will lead to this error,please teach me how to slove it**

##### By the way, in my opinion,the inage maybe have error
url:https://github.com/openkruise/rollouts/blob/master/docs/images/rollout_canary.png
Canary Releases should be allocated less traffic，but in image allocated 95% traffic to new version service .Don't be offended if my opinion is incorrect
@zmberg

**Comment by xiao-jay** [comment]
i found the reason,the luaJIT is not support mac m1,it should update to laterest

**Comment by FillZpp** [comment]
@xiao-jay `cilium/echoserver` only supports amd64, you can find it [here](https://hub.docker.com/r/cilium/echoserver/tags).

**Comment by xiao-jay** [comment]
ok，thanks your response

**Comment by xiao-jay** [comment]
Can i ask a question,the image ```cilium/echoserver``` it has possible to support m1?  In addition to luaJIT, there may be other unsupported component?

**Comment by veophi** [comment]
> Can i ask a question,the image `cilium/echoserver` it has possible to support m1? In addition to luaJIT, there may be other unsupported component?

Are you looking for an example to  test Kruise Rollout?

**Comment by xiao-jay** [comment]
yeap, a example can test in m1.

**Comment by veophi** [comment]
Maybe you can try to find an arm version of echoserver in the docker hub, such as https://hub.docker.com/layers/echoserver/e2eteam/echoserver/2.2-linux-arm64/images/sha256-182946594ca7b472af35d247321842f05a5a43f3f4d0821e31af8bb269b8e048?context=explore

**Comment by xiao-jay** [comment]
> Maybe you can try to find an arm version of echoserver in the docker hub, such as https://hub.docker.com/layers/echoserver/e2eteam/echoserver/2.2-linux-arm64/images/sha256-182946594ca7b472af35d247321842f05a5a43f3f4d0821e31af8bb269b8e048?context=explore

thank you ,this is a good suggestion for me

**Comment by xiao-jay** [comment]
---
By the way, in my opinion,the image maybe have error
url:https://github.com/openkruise/rollouts/blob/master/docs/images/rollout_canary.png
Canary Releases should be allocated less traffic，but in image allocated 95% traffic to new version service .Don't be offended if my opinion is incorrect

Nobody see my last sentence，i am sorry put the question last.

**Comment by xiao-jay** [comment]
> i change image from cilium/echoserver:1.10.2 to e2eteam/echoserver:2.2-linux-arm,this image can support m1
> 
> when i use `kubectl apply -f rollout.yaml(2. Deploy Kruise Rollout CRD)` i get this error
> 
> ```
> ➜  kubenetes kubectl apply -f rollout.yaml                                   
> error: error validating "rollout.yaml": error validating data: [ValidationError(Rollout.spec.objectRef): unknown field "type" in io.kruise.rollouts.v1alpha1.Rollout.spec.objectRef, ValidationError(Rollout.spec.strategy): unknown field "type" in io.kruise.rollouts.v1alpha1.Rollout.spec.strategy]; if you choose to ignore these errors, turn validation off with --validate=false
> ```
> 
> but i found type io.kruise.rollouts.v1alpha1.Rollout.spec.objectRef in `https://github.com/openkruise/rollouts/blob/master/api/v1alpha1/rollout_types.go#L38`.I dont know why will lead to `unknown field "type"` error

i found add ```---validate=false```  does not affect normal use .
