### ISSUE TITLE
cloneset use kruise-rollout 

### ISSUE THREAD

**Issue by skyshaokai** [openkruise/rollouts#49]
I use  kruise-rollout  on cloneset （InPlaceIfPossible） .  when i  "describe  rollouts " get info :
<img width="917" alt="image" src="https://user-images.githubusercontent.com/11512967/175915727-7891a0e0-2244-4fb5-aca8-64adbd195207.png">

I found the rollout process strange. step 2 and step 3 upgrade at same time. Why is there no time difference ?  Shouldn't each step wait for the new version of pod to be launched?

**Comment by zmberg** [comment]
Because pause.duration = 0. I think you should set a bigger value.
