### ISSUE TITLE
How to manually pause the online process of kruise rollout?

### ISSUE THREAD

**Issue by skyshaokai** [openkruise/rollouts#55]
How to manually pause the online process of kruise rollout?

I try to force the setting of status Currentstepstate is: steppaused. 
I tried to pause the execution of rollout and found that it had no effect. How can I pause manually?
<img width="291" alt="image" src="https://user-images.githubusercontent.com/11512967/178271370-82a9baa5-b0a0-48b3-b0cc-e2f7566e62e2.png">

**Comment by zmberg** [comment]
currently you can set spec.strategy.paused=true to pause rollout progressing.

**Comment by skyshaokai** [comment]
> currently you can set spec.strategy.paused=true to pause rollout progressing.

we use cloneset do you mean  , set  cloneset  spec.strategy.paused=true ?
