### ISSUE TITLE
Is there a plan to support DaemonSet？

### ISSUE THREAD

**Issue by liulangwa** [openkruise/rollouts#69]
Is there a plan to support DaemonSet？Is there a specific roadmap?

**Comment by zmberg** [comment]
There is planned support, but the kruise daemonSet. The native daemonset is more difficult.

**Comment by liulangwa** [comment]
can support kruise daemonSet  first

**Comment by zmberg** [comment]
@liulangwa The code is being implemented and will be ready in the next two months.

**Comment by fengshunli** [comment]
Can be assigned to me to complete this requirement together @zmberg

**Comment by furykerry** [comment]
the feature is completed in the pr:
https://github.com/openkruise/rollouts/pull/134
